"monitored_hosts":
  "api":
    "exporters":
    - "node"
    "hostname": "api"
    "ip": "10.0.1.47"
  "db":
    "exporters":
    - "node"
    - "mysql"
    "hostname": "db"
    "ip": "10.0.1.196"
  "discord-bot":
    "exporters":
    - "node"
    "hostname": "discord-bot"
    "ip": "10.0.1.136"
  "game-server":
    "exporters":
    - "node"
    "hostname": "game-server"
    "ip": "10.0.1.48"
  "gapi":
    "exporters":
    - "node"
    "hostname": "gapi"
    "ip": "10.0.1.38"
  "github-runner-homelab-01":
    "exporters":
    - "node"
    "hostname": "github-runner-homelab-01"
    "ip": "10.0.1.127"
  "github-runner-litbot-01":
    "exporters":
    - "node"
    "hostname": "github-runner-litbot-01"
    "ip": "10.0.1.41"
  "github-runner-org-01":
    "exporters":
    - "node"
    "hostname": "github-runner-org-01"
    "ip": "10.0.1.94"
  "homepage":
    "exporters":
    - "node"
    "hostname": "homepage"
    "ip": "10.0.1.180"
  "media-arr":
    "exporters":
    - "node"
    "hostname": "media-arr"
    "ip": "10.0.1.206"
  "monitoring":
    "exporters":
    - "node"
    "hostname": "monitoring"
    "ip": "10.0.1.87"
  "site":
    "exporters":
    - "node"
    "hostname": "site"
    "ip": "10.0.1.165"
  "tfstate-minio":
    "exporters":
    - "node"
    "hostname": "tfstate-minio"
    "ip": "10.0.1.120"
  "traefik":
    "exporters":
    - "node"
    "hostname": "traefik"
    "ip": "10.0.1.123"
"proxmox_nodes_list":
- "exporters":
  - "node"
  "hostname": "arcanine"
  "ip": "10.0.1.110"
- "exporters":
  - "node"
  "hostname": "fuecoco"
  "ip": "10.0.1.113"
- "exporters":
  - "node"
  "hostname": "growlithe"
  "ip": "10.0.1.111"
- "exporters":
  - "node"
  "hostname": "murkrow"
  "ip": "10.0.1.114"
- "exporters":
  - "node"
  "hostname": "pawmot"
  "ip": "10.0.1.112"
