"homepage_containers":
  "api":
    "icon": "php.png"
    "ip": "10.0.1.47"
    "name": "api"
    "node": "arcanine"
    "vmid": 1001
  "db":
    "icon": "mariadb.png"
    "ip": "10.0.1.196"
    "name": "db"
    "node": "arcanine"
    "vmid": 1000
  "game-server":
    "icon": "amp.png"
    "ip": "10.0.1.48"
    "name": "game-server"
    "node": "pawmot"
    "vmid": 1007
  "gapi":
    "icon": "php.png"
    "ip": "10.0.1.38"
    "name": "gapi"
    "node": "arcanine"
    "vmid": 1002
  "homepage":
    "icon": "homepage.png"
    "ip": "10.0.1.178"
    "name": "homepage"
    "node": "arcanine"
    "vmid": 1004
  "monitoring":
    "icon": "grafana.png"
    "ip": "10.0.1.87"
    "name": "monitoring"
    "node": "arcanine"
    "vmid": 1006
  "site":
    "icon": "php.png"
    "ip": "10.0.1.166"
    "name": "site"
    "node": "arcanine"
    "vmid": 1003
