"homepage_containers":
  "api":
    "icon": "php.png"
    "ip": "10.0.1.47"
    "name": "api"
    "node": "arcanine"
    "vmid": 1001
  "db":
    "icon": "mariadb.png"
    "ip": "10.0.1.196"
    "name": "db"
    "node": "arcanine"
    "vmid": 1000
  "game-server":
    "icon": "amp.png"
    "ip": "10.0.1.48"
    "name": "game-server"
    "node": "pawmot"
    "vmid": 1007
  "gapi":
    "icon": "php.png"
    "ip": "10.0.1.38"
    "name": "gapi"
    "node": "arcanine"
    "vmid": 1002
  "github-runner":
    "icon": "github.png"
    "ip": "10.0.1.182"
    "name": "github-runner"
    "node": "growlithe"
    "vmid": 1010
  "github-runner-personal":
    "icon": "github.png"
    "ip": "10.0.1.131"
    "name": "github-runner-personal"
    "node": "growlithe"
    "vmid": 1011
  "homepage":
    "icon": "homepage.png"
    "ip": "10.0.1.178"
    "name": "homepage"
    "node": "arcanine"
    "vmid": 1004
  "monitoring":
    "icon": "grafana.png"
    "ip": "10.0.1.73"
    "name": "monitoring"
    "node": "arcanine"
    "vmid": 1006
  "site":
    "icon": "php.png"
    "ip": "10.0.1.166"
    "name": "site"
    "node": "arcanine"
    "vmid": 1003
  "traefik":
    "icon": "traefik.png"
    "ip": "10.0.1.165"
    "name": "traefik"
    "node": "arcanine"
    "vmid": 1005
