"all":
  "children":
    "api_servers":
      "hosts":
        "api":
          "ansible_host": "10.0.1.47"
          "ansible_user": "root"
        "gapi":
          "ansible_host": "10.0.1.38"
          "ansible_user": "root"
    "monitoring":
      "hosts":
        "monitoring":
          "ansible_host": "10.0.1.73"
          "ansible_user": "root"
    "mysql_exporters":
      "hosts":
        "db":
          "ansible_host": "10.0.1.196"
          "ansible_user": "root"
    "mysql_servers":
      "hosts":
        "db":
          "ansible_host": "10.0.1.196"
          "ansible_user": "root"
    "node_exporters":
      "hosts":
        "api":
          "ansible_host": "10.0.1.47"
          "ansible_user": "root"
        "db":
          "ansible_host": "10.0.1.196"
          "ansible_user": "root"
        "game-server":
          "ansible_host": "10.0.1.41"
          "ansible_user": "root"
        "gapi":
          "ansible_host": "10.0.1.38"
          "ansible_user": "root"
        "homepage":
          "ansible_host": "10.0.1.178"
          "ansible_user": "root"
        "monitoring":
          "ansible_host": "10.0.1.73"
          "ansible_user": "root"
        "site":
          "ansible_host": "10.0.1.166"
          "ansible_user": "root"
        "traefik":
          "ansible_host": "10.0.1.165"
          "ansible_user": "root"
    "proxmox_node_exporters":
      "hosts":
        "arcanine":
          "ansible_host": "10.0.1.110"
          "ansible_user": "root"
        "fuecoco":
          "ansible_host": "10.0.1.113"
          "ansible_user": "root"
        "growlithe":
          "ansible_host": "10.0.1.111"
          "ansible_user": "root"
        "murkrow":
          "ansible_host": "10.0.1.114"
          "ansible_user": "root"
        "pawmot":
          "ansible_host": "10.0.1.112"
          "ansible_user": "root"
    "proxmox_nodes":
      "hosts":
        "arcanine":
          "ansible_host": "10.0.1.110"
          "ansible_user": "root"
        "fuecoco":
          "ansible_host": "10.0.1.113"
          "ansible_user": "root"
        "growlithe":
          "ansible_host": "10.0.1.111"
          "ansible_user": "root"
        "murkrow":
          "ansible_host": "10.0.1.114"
          "ansible_user": "root"
        "pawmot":
          "ansible_host": "10.0.1.112"
          "ansible_user": "root"
    "ungrouped":
      "hosts":
        "game-server":
          "ansible_host": "10.0.1.41"
          "ansible_user": "root"
        "homepage":
          "ansible_host": "10.0.1.178"
          "ansible_user": "root"
        "site":
          "ansible_host": "10.0.1.166"
          "ansible_user": "root"
        "traefik":
          "ansible_host": "10.0.1.165"
          "ansible_user": "root"
      "vars":
        "ansible_port": 22
        "ansible_python_interpreter": "/usr/bin/python3"
  "vars":
    "ansible_ssh_common_args": "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
