"all":
  "children":
    "api_servers":
      "hosts":
        "api":
          "ansible_host": "10.0.1.238"
          "ansible_user": "root"
        "gapi":
          "ansible_host": "10.0.1.68"
          "ansible_user": "root"
    "mysql_servers":
      "hosts":
        "db":
          "ansible_host": "10.0.1.222"
          "ansible_user": "root"
    "ungrouped":
      "hosts":
        "site":
          "ansible_host": "10.0.1.99"
          "ansible_user": "root"
      "vars":
        "ansible_port": 22
        "ansible_python_interpreter": "/usr/bin/python3"
  "vars":
    "ansible_ssh_common_args": "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
