---
# Main provisioning playbook
- name: Configure base system
  import_playbook: ../roles/base/main.yml

- name: Configure API server
  import_playbook: php-server.yml

- name: Configure MySQL server
  import_playbook: mysql-server.yml