---
# Main provisioning playbook
- name: Configure base system
  import_playbook: ../roles/base/main.yml

- name: Configure PHP server
  import_playbook: php-server.yml

- name: Configure MySQL server
  import_playbook: mysql-server.yml

- name: Deploy Traefik reverse proxy
  import_playbook: traefik.yml

- name: Deploy monitoring exporters
  import_playbook: exporter-deployment.yml

#- name: Deploy GitHub Actions runners
#  import_playbook: github-runner.yml

- name: Configure API server
  import_playbook: api.yml

- name: Configure GAPI server
  import_playbook: gapi.yml

- name: Configure game server
  import_playbook: game-server.yml

- name: Configure homepage server
  import_playbook: homepage.yml
  
- name: Configure monitoring stack
  import_playbook: monitoring.yml

- name: Validate monitoring stack
  import_playbook: validate.yml